Website = "https://github.com/zquestz/fortunate"

[Details]
  Icon = "Icon.png"
  Name = "Fortunate"
  ID = "at.greyh.fortunate"
  Version = "1.1.1"
  Build = 1

[LinuxAndBSD]
  Categories = ["Utility"]
  Comment = "Beautiful motivation/fortune app"
